import "~/styles/globals.css";
import { Onest } from "next/font/google";
import { TRPCReactProvider } from "~/trpc/react";
import Script from "next/script";

const onest = Onest({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`font-sans ${onest.variable}`}>
				<Script
					src="https://eu.umami.is/script.js"
					strategy="worker"
					data-website-id="51efa585-c6e8-4bc2-a6c5-3b482aed079f"
				/>
				<TRPCReactProvider>{children}</TRPCReactProvider>
			</body>
		</html>
	);
}
