import { font } from '@/styles/font'
import '@/styles/globals.css'
import { TRPCReactProvider } from '@/trpc/react'
import Script from 'next/script'

export const metadata = {
	title: 'Create T3 App',
	description: 'Generated by create-t3-app',
	icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en" className="dark">
			<body className={font}>
				<Script
					src="https://eu.umami.is/script.js"
					data-website-id="51efa585-c6e8-4bc2-a6c5-3b482aed079f"
				/>

				<TRPCReactProvider>{children}</TRPCReactProvider>
			</body>
		</html>
	)
}
